require('module-config')

caffeinateOnIcon = [[ASCII:
.....1a..........AC..........E
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
.....5c.......................
]]

caffeinateOffIcon = [[ASCII:
.....1a.....x....AC.y.......zE
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
...x.5c....y.......z..........
]]

local caffeinateTrayIcon = hs.menubar.new()

local function caffeinateSetIcon(state)
  caffeinateTrayIcon:setIcon(state and caffeinateOnIcon or caffeinateOffIcon)
end

local function toggleCaffeinate()
  local sleepStatus = hs.caffeinate.toggle("displayIdle")
  if sleepStatus then
    myNotify("System never sleep")
  else
    myNotify("System will sleep when idle")
  end

  caffeinateSetIcon(sleepStatus)
end

hs.hotkey.bind(hyper, "=", toggleCaffeinate)
caffeinateTrayIcon:setClickCallback(toggleCaffeinate)
caffeinateSetIcon(false)
